travis:
  secure:
    BINSTAR_TOKEN: QnatJGKppTi7RJxmaTiNAJo+kn63jRDOFxw0O4j+SE3ia22tHqWcRk8VrVY0YTHJanPz6lVxh7PY9FULvyk9z0cx6/H/Y/pORfUJ5YdVoGA/ru3fzmlsTfRoKBRc2bXVLh3gkvjRAoICvWuq8T8FUYIe8yV/Bhmdg3ayGsXEsjvekWRAfZJnZfLVdOxGF2/P7X6RPxXYzqoeqhG6T+i3IWhapdefUj9MpBdMnY4mgiNimo/OG9eY22HbE/03pt4f5MVBMLf9KwwSyRe2HRGwO6hQ+dx5iVMqlckHW/WYN1irIlEWMrdh+ip+xiSY/bpQC80Ea4snXGxRiQXEaFq5NPTB55s3mr9XBsFVTRiXawvfkUDsb+zKE8Se6CeVbn6nE2emHQp+J0aMZSU/mgqJxLpbTc3OqHJaRZWCzHEnATil4RAsFSs1vgOfhK3J0NwjCpOOmwF73Uim6mkvicFEqdkiNxSyhFyfT9PEoikflQiQoQDF8t6CJ5x20WB2jIU3gwI1t2GYKblbA3EzVL4YxaU5JqdBmkkzHZHnuZzwbyifE2G5PTfg+qc6b6jZh8adxPY3JoD8Vns3DClWeOTH4B5nXeFSaeARpL1xt+tlOdZv938hMAfFnOvHKZWk3hCoqKx/qlSxrmfyglDUI7vtBd7eX01JvdFaD37CBByTM7c=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
