travis:
  secure:
    BINSTAR_TOKEN: EBkvKjzlHDfFBnhYRgq0gq9VTWZEcgPEZjSbFeAAIxHlfX+z0fWcGOTYiKl2QUNyemfajxgL0ITfa6cQ8wPKIyYNYmXpbRlDUoV8jJMPadMqiKMr4ULC9wdbLjPaJzIymqEAbyWgsCKX6IUkqlbRTSg4hxsK6EPPXis8btFqKjOp1fq/8x3UK3atkJ8Sj0Wu75n4tCh03YkjE2Yq78BUhasCAp4PhSgEaqF9o6I9zzrZiJHaHJNTOGIDiFkRtFWK/MYesWSD5ZnuzbW1l15sfCPPKcYDjyXvrS+mvA/mWXFrAYpMofTR6rjMmUm3jgi5pD1UsqDD7F58+MGRx1SgO91mmIV17AJ5c9lotzTEWRCwk/fYO3ju+kvdJSebMUq+NP8bjHsmndihhDe57EYOS6QuIpPGufoZMGdyCNPWVSM1w42cPe4mrnF2uy1j16zphxhEqN14ilndg8QZ8KUw02ZQ/nptjIoPmR4XchVYcGEcFWu3QPCRBSpmI8ozs0ij00f7d/34uHin1buCdD6VZ5wHzhRJEr71Fg6n2AcG9gIPNzPBPcSVIT3AFSfTodoxIjb1W4VQqFxGDMJ/UktwA5C6EKvS2Mi5TWiQ2VHkVMKDn3yB5cNLx9eMD3+TbBdhNcmP9Sx3fgbTU4yxtbOot02FImqrGht9gBYzhyDQmRk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
